<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Cron', 'base');

/**
 * Table_Cron
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_cron
 * @property string  $service
 * @property boolean $is_active
 * @property string $description
 * @property timestamp $last_execution_at
 * @property integer $frequency
 * 
 * @method integer getId()
 * @method boolean isNew()
 * @method static Cron find($id, $tableName = null)
 * @method static Cron findOneBy*
 * @static Doctrine_Collection findBy*
 * 
 * @method static getIdCronById() getIdCronById($id)
 * @method getIdCron() getIdCron()
 * @method setIdCron() setIdCron($value)
 * @method static getServiceById() getServiceById($id)
 * @method getService() getService()
 * @method setService() setService($value)
 * @method static getIsActiveById() getIsActiveById($id)
 * @method getIsActive() getIsActive()
 * @method setIsActive() setIsActive($value)
 * @method static getDescriptionById() getDescriptionById($id)
 * @method getDescription() getDescription()
 * @method setDescription() setDescription($value)
 * @method static getLastExecutionAtById() getLastExecutionAtById($id)
 * @method getLastExecutionAt() getLastExecutionAt()
 * @method setLastExecutionAt() setLastExecutionAt($value)
 * @method static getFrequencyById() getFrequencyById($id)
 * @method getFrequency() getFrequency()
 * @method setFrequency() setFrequency($value)
 * 
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Table_Cron extends Base_Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('cron');
        $this->hasColumn('id_cron', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'can_import' => true,
             ));
        $this->hasColumn('service', 'string ', 255, array(
             'type' => 'string ',
             'length' => '255',
             'can_import' => true,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'can_import' => true,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'can_import' => true,
             ));
        $this->hasColumn('last_execution_at', 'timestamp', null, array(
             'type' => 'timestamp',
             'default' => 'notnull',
             'can_import' => true,
             ));
        $this->hasColumn('frequency', 'integer', null, array(
             'type' => 'integer',
             'can_import' => true,
             ));

        $this->option('service', false);
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}