<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DatabaseChangelog', 'base');

/**
 * Table_DatabaseChangelog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string  $id_database_changelog
 * @property timestamp $executed_at
 * @property string $module
 * @property integer $type
 * 
 * @method integer getId()
 * @method boolean isNew()
 * @method static Database_changelog find($id, $tableName = null)
 * @method static Database_changelog findOneBy*
 * @static Doctrine_Collection findBy*
 * 
 * @method static getIdDatabaseChangelogById() getIdDatabaseChangelogById($id)
 * @method getIdDatabaseChangelog() getIdDatabaseChangelog()
 * @method setIdDatabaseChangelog() setIdDatabaseChangelog($value)
 * @method static getExecutedAtById() getExecutedAtById($id)
 * @method getExecutedAt() getExecutedAt()
 * @method setExecutedAt() setExecutedAt($value)
 * @method static getModuleById() getModuleById($id)
 * @method getModule() getModule()
 * @method setModule() setModule($value)
 * @method static getTypeById() getTypeById($id)
 * @method getType() getType()
 * @method setType() setType($value)
 * 
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Table_DatabaseChangelog extends Base_Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('database_changelog');
        $this->hasColumn('id_database_changelog', 'string ', 64, array(
             'type' => 'string ',
             'primary' => true,
             'length' => '64',
             'can_import' => true,
             ));
        $this->hasColumn('executed_at', 'timestamp', null, array(
             'type' => 'timestamp',
             'can_import' => true,
             ));
        $this->hasColumn('module', 'string', null, array(
             'type' => 'string',
             'can_import' => true,
             ));
        $this->hasColumn('type', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'can_import' => true,
             ));

        $this->option('service', false);
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}