<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AclRole', 'base');

/**
 * Table_AclRole
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_acl_role
 * @property string  $object
 * @property integer $order
 * @property boolean $is_visible
 * @property string  $name
 * @property string  $name_role
 * @property integer $id_service
 * 
 * @method integer getId()
 * @method boolean isNew()
 * @method static Acl_role find($id, $tableName = null)
 * @method static Acl_role findOneBy*
 * @static Doctrine_Collection findBy*
 * 
 * @method static getIdAclRoleById() getIdAclRoleById($id)
 * @method getIdAclRole() getIdAclRole()
 * @method setIdAclRole() setIdAclRole($value)
 * @method static getObjectById() getObjectById($id)
 * @method getObject() getObject()
 * @method setObject() setObject($value)
 * @method static getOrderById() getOrderById($id)
 * @method getOrder() getOrder()
 * @method setOrder() setOrder($value)
 * @method static getIsVisibleById() getIsVisibleById($id)
 * @method getIsVisible() getIsVisible()
 * @method setIsVisible() setIsVisible($value)
 * @method static getNameById() getNameById($id)
 * @method getName() getName()
 * @method setName() setName($value)
 * @method static getNameRoleById() getNameRoleById($id)
 * @method getNameRole() getNameRole()
 * @method setNameRole() setNameRole($value)
 * @method static getIdServiceById() getIdServiceById($id)
 * @method getIdService() getIdService()
 * @method setIdService() setIdService($value)
 * 
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Table_AclRole extends Base_Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('acl_role');
        $this->hasColumn('id_acl_role', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'can_import' => true,
             ));
        $this->hasColumn('object', 'string ', 255, array(
             'type' => 'string ',
             'length' => '255',
             'can_import' => true,
             ));
        $this->hasColumn('order', 'integer', null, array(
             'type' => 'integer',
             'can_import' => true,
             ));
        $this->hasColumn('is_visible', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             'can_import' => true,
             ));
        $this->hasColumn('name', 'string ', 255, array(
             'type' => 'string ',
             'notnull' => true,
             'length' => '255',
             'can_import' => true,
             ));
        $this->hasColumn('name_role', 'string ', 255, array(
             'type' => 'string ',
             'notnull' => true,
             'length' => '255',
             'can_import' => true,
             ));
        $this->hasColumn('id_service', 'integer', null, array(
             'type' => 'integer',
             'can_import' => false,
             'log' => false,
             ));

        $this->option('orderBy', 'order ASC');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}