<?php

/**
 * Layout
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Layout extends Table_Layout
{
    private $_data_map = null;


    /**
     * @param array $options
     * @return Doctrine_Query
     */
    public static function getQuery($options = array())
    {
        $options['id_service'] = null;

        $query = parent::getQuery($options);


        if(isset($options['type']) && strlen($options['type']) > 0 ){
            $query->addWhere('o.type = ?', $options['type']);
        }

        if(isset($options['id_user_or_public']) && strlen($options['id_user_or_public']) > 0 ){
            $query->addWhere('(o.id_user = ? OR o.is_public = 1)', $options['id_user_or_public']);
        }

        if(isset($options['id_user']) && strlen($options['id_user']) > 0 ){
            $query->addWhere('o.id_user = ?', $options['id_user']);
        }

        if(isset($options['is_default']) && strlen($options['is_default']) > 0 ){
            $query->addWhere('o.is_default = ?', (bool)$options['is_default']);
        }

        return $query;
    }




    public function getDataMap()
    {
        if(null === $this->_data_map)
        {
            $this->_data_map = (array) @json_decode(parent::getDataMap(), true);
        }

        return $this->_data_map;
    }


    public function setDataMap($value)
    {
        $this->_data_map = $value;

        return parent::setDataMap(json_encode($this->_data_map));
    }
    
//    public function setIsDefault($value)
//	{
//		if($value && $this->getIsDefault() == 0){
//			Doctrine_Query::create()->update('Layout')->set('is_default', '0')->execute();
//		}
//
//		parent::setIsDefault($value);
//		return $this;
//	}

//    public static function getListArray($options=null)
//    {
//    	$result = self::getList((array)$options + array('is_edit' => 1, 'is_dashboard'=> 0, 'order' => 'module,name'));
//
//        $listOptions = array();
//    	foreach ($result as $row) {
//    		$listOptions[$row['module']][$row['id_layout']] = $row['name'];
//    	}
//
//        return $listOptions;
//    }


    public function postSave($event)
    {
        Base_Layout::cleanCache();
        parent::postSave($event);
    }

    public function postDelete($event)
    {
        Base_Layout::cleanCache();
        parent::postDelete($event);
    }

}