<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pl" lang="pl">
<head>
	<meta http-equiv="content-type" content="text/html;charset=utf-8" />
</head>
<body>
	<table border="0" style="border: 0; width: 800px; font-family: Verdana, Arial, Helvetica, sans-serif; color:#354751;" width="800">
		<tr>
			<td>
				<?=$this->mail_content;?>
			</td>
		</tr>
	</table>
</body>
</html>