<?php echo $this->doctype() ?>
<html lang="en" id="extr-page">
<head>
    <link rel="stylesheet" type="text/css" media="screen" href="/assets/css/bootstrap.css">
    <link rel="stylesheet" type="text/css" media="screen" href="/assets/css/library/fontawesome/font-awesome.css">

    <!-- SmartAdmin Styles : Caution! DO NOT change the order -->
    <link rel="stylesheet" type="text/css" media="screen" href="/assets/css/smartadmin-production-plugins.css">
    <link rel="stylesheet" type="text/css" media="screen" href="/assets/css/smartadmin-production.css">
    <link rel="stylesheet" type="text/css" media="screen" href="/assets/css/smartadmin-skins.css">

    <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=latin,latin-ext">

    <?=$this->render('_metadata-links.phtml')?>

    <?php $this->headScript()
        ->prependFile('/assets/lib/bootstrap/js/bootstrap.min.js')
        ->prependFile('/assets/lib/jquery/jquery.last.min.js')
    ; ?>

    <?php echo $this->headTitle(); ?>
    <?php echo $this->headMeta()->toString() . "\r\n" ?>
</head>
<body>
<header id="header">
    <h1 style="width: 100%" class="col-md-12">
        <?= $this->pageMainTitle; ?>
    </h1>
</header>
<div id="main" role="main">
    <div id="content" class="container">
        <div class="row">
            <div class=" col-lg-12  col-md-10 col-sm-12">
                <div class="row">

                        <div class="col-sm-12 ">
                            <?= $this->flashMessages(); ?>
                            <?php echo $this->layout()->content ?>
                        </div>
                </div>
            </div>
        </div>
    </div>
</div>

<?php echo $this->headScript(); ?>
</body>
</html>
