<?php

/**
 * Language
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Language extends Table_Language
{


    /*
     * static function return array of languages available indexed by code
     * @static
     * @return array()
     */
    public static function getAvailableLanguages()
    {
        return Doctrine_Query::create()
            ->from(__CLASS__.' INDEXBY code')
            ->where('is_active = 1')
            ->execute(array(), Doctrine::HYDRATE_ARRAY);

    }

    public static function getAvailableLanguagesArray()
    {
        return Doctrine_Query::create()
            ->from(__CLASS__)
            ->where('is_active = 1')
            ->execute()
            ->toKeyValueArray('id_language', 'name');
    }


    public function postSave($event)
    {
        parent::postSave($event);
        Base_Cache::clean();
    }

    public function postDelete($event)
    {
        parent::postDelete($event);
        Base_Cache::clean();
    }

}