<?php

/**
 * Query
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Query extends Table_Query
{
    /**
     * @var $list array
     */
    private static $_list = array();


    public static function getQuery($options = array())
    {
        $query = parent::getQuery($options);

        if(isset($options['form']) && strlen($options['form']) > 0){
            $query->addWhere('o.form = ?', $options['form']);
        }

        if(isset($options['id_user']) && strlen($options['id_user']) > 0){
            $query->addWhere('o.id_user = ?', $options['id_user']);
        }else{
            $query->addWhere('o.id_user = ? OR o.is_public = 1', Base_Auth::getUserId());
        }

        return $query;
    }

    public static function getList($options = array())
    {
        $listQuery = self::getQuery($options)->execute();

        foreach($listQuery as $element){
            self::$_list[$element['id_query']] = $element;
        }

        return self::$_list;
    }


    /**
     * @param $value
     * @param null $id_language
     * @return $this
     * @throws Doctrine_Query_Exception
     */
    public function setIsDefault($value, $id_language = null)
    {
        if($value){
            $id_user = $this->id_user ? $this->id_user : Base_Auth::getUserId();

            Doctrine_Query::create()->update(__CLASS__)
                ->set('is_default', '0')
                ->where('id_user = ? AND form = ?', array($id_user, $this->form))
                ->execute();
        }

        parent::setIsDefault($value, $id_language);
        return $this;
    }


    /**
     * @param $event
     */
    public function preInsert($event)
    {
        parent::preInsert($event);

        if(!$this->id_user){ $this->id_user = Base_Auth::getUserId(); }
    }

}