<?php

/**
 * Session
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Session extends Table_Session
{

    public static $time_online_sec = 600;

    /**
     * @param array $options
     * @return Doctrine_Query
     */
    public static function getQuery($options = array())
    {
        $options['select'] = isset($options['select']) ? $options['select'] : 'o.*, IF(o.modified > UNIX_TIMESTAMP(now() - SEC_TO_TIME('.self::$time_online_sec.')), 1, 0) as is_online';

        $query = parent::getQuery($options);


        return $query;
    }

    /**
     * @param $event
     */
    public function postDelete($event)
    {
        parent::postDelete($event);

        if($this->id_user){
            Log::addLog(Log::TYPE_LOGOUT_TIMEOUT, null, array(
                'model' => 'User', 'id_user' => $this->id_user, 'id_object' => $this->id_user
            ));
        }
    }

}