<div style="display: none;" id="generateLinkOverboxBody">

    <dl class="dl-horizontal">
        <dt class="padding-top-10"><i class="fa fa-refresh fa-3x txt-color-greenLight"></i></dt>
        <dd><h3 class="no-margin">Czy chcesz wygenerować nowy link do automatycznego logowania?</h3></dd>
    </dl>

</div>

<div style="display: none;" id="disableLinkOverboxBody">

    <dl class="dl-horizontal">
        <dt class="padding-top-10"><i class="fa fa-power-off fa-3x txt-color-red"></i></dt>
        <dd><h3 class="no-margin">Czy chcesz wyłączyć możliwość automatycznego logowania?</h3></dd>
    </dl>

</div>